{
 "title": "Someguy",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(delegated_routing_server_http_request_duration_seconds_count{job=\"someguy\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "libp2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (transport) (libp2p_swarm_connections_opened_total{job=\"someguy\", instance=~\"$instance\"}) - sum by (transport) (libp2p_swarm_connections_closed_total{job=\"someguy\", instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Inflight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(delegated_routing_server_http_requests_inflight{job=\"someguy\", instance=~\"$instance\"}) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration by http handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, handler) (rate(delegated_routing_server_http_request_duration_seconds_bucket{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P99 {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, handler) (rate(delegated_routing_server_http_request_duration_seconds_bucket{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P95 {{handler}}"
    }
   ]
  },
  {
   "title": "Request rate by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(delegated_routing_server_http_request_duration_seconds_count{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(delegated_routing_server_http_request_duration_seconds_count{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval])) by (code, handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cached Address Book", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Peer cache lookups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(someguy_cached_router_peer_addr_lookups{job=\"someguy\", instance=~\"$instance\", origin=\"providers\"}[$__rate_interval])) by (cache)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer State Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(someguy_cached_addr_book_peer_state_size{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval]) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probed Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(someguy_cached_addr_book_probed_peers{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval])) by (result, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe Loop Duration (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, instance) (rate(someguy_cached_addr_book_probe_duration_seconds_bucket{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "P99 {{instance}}"
    }
   ]
  },
  {
   "title": "Golang",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(go_goroutines{job=\"someguy\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum(go_threads{job=\"someguy\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(go_memstats_alloc_bytes{job=\"someguy\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}} - bytes allocated"
      },
      {
       "expr": "sum(rate(go_memstats_alloc_bytes_total{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - alloc rate"
      },
      {
       "expr": "sum(go_memstats_stack_inuse_bytes{job=\"someguy\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}} - stack in use"
      },
      {
       "expr": "sum(go_memstats_heap_inuse_bytes{job=\"someguy\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}} - heap in use"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(process_resident_memory_bytes{job=\"someguy\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - resident"
      },
      {
       "expr": "sum(process_virtual_memory_bytes{job=\"someguy\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}} - virtual"
      }
     ]
    }
   ]
  }
 ]
}